Repository TeamMascota/Mascota-Android, pull requests merged in 2021-07, with the labels that each got.

#14 Feature/8 init home fragment
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/home/BindingConversions.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/HomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/LocalHomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomeBookInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: Done, P0, Review Required, 🐱 onpyeong

#15 Feature/10 custom calendar
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/MascotaApplication.kt
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/SingletonModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/calendar/CalendarFragment.kt
  app/src/main/java/org/mascota/ui/view/calendar/data/datasource/CalendarDataSource.kt
  app/src/main/java/org/mascota/ui/view/calendar/data/datasource/LocalCalendarDataSource.kt
  app/src/main/java/org/mascota/ui/view/calendar/data/model/CalendarData.kt
  app/src/main/java/org/mascota/ui/view/custom/CalendarView.kt
  app/src/main/java/org/mascota/ui/view/custom/MonthView.kt
  app/src/main/java/org/mascota/ui/view/custom/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/org/mascota/ui/viewmodel/CalendarViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/java/org/mascota/util/CalendarUtil.kt
  app/src/main/java/org/mascota/util/PixelRatio.kt
  app/src/main/java/org/mascota/util/extension/ResourceExt.kt
  app/src/main/java/org/mascota/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_dog_angry.xml
  app/src/main/res/drawable/ic_dog_boring.xml
  app/src/main/res/drawable/ic_dog_joy.xml
  app/src/main/res/drawable/ic_dog_love.xml
  app/src/main/res/drawable/ic_dog_sad.xml
  app/src/main/res/drawable/ic_dog_usual.xml
  app/src/main/res/drawable/ic_double_arrow_left.xml
  app/src/main/res/drawable/ic_double_arrow_right.xml
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/drawable/oval_orange_alpha_90.xml
  app/src/main/res/drawable/rectangle_fill_gray_left_3.xml
  app/src/main/res/drawable/rectangle_fill_gray_right_3.xml
  app/src/main/res/drawable/rectangle_fill_orange_left_3.xml
  app/src/main/res/drawable/rectangle_fill_orange_right_3.xml
  app/src/main/res/drawable/selector_switch_btn_left.xml
  app/src/main/res/drawable/selector_switch_btn_right.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/layout/layout_calendar_top.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: In Progress, P0, 🐶 mdb1217

#16 Feature/12 custom book
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/home/BindingConversions.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/HomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/LocalHomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomeDiaryInfoData.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomePageInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/res/drawable-v24/rectangle_orange_radius_3.xml
  app/src/main/res/drawable/oval_white.xml
  app/src/main/res/drawable/rectangle_orange_radius_0.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/layout_book_diary.xml
  app/src/main/res/layout/layout_diary_write.xml
  app/src/main/res/layout/view_custom_book.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#19 Feature/17 home fragment recycler view
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/adapter/HomeContentAdapter.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/HomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/LocalHomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomeContentInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_content.xml
  app/src/main/res/layout/layout_diary_write.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, 🐱 onpyeong

#21 Feature/13 profile create UI
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/custom/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/org/mascota/ui/view/custom/calendar/CalendarView.kt
  app/src/main/java/org/mascota/ui/view/custom/calendar/MonthView.kt
  app/src/main/java/org/mascota/ui/view/custom/profile/ProfileBottomSheetDialog.kt
  app/src/main/java/org/mascota/ui/view/profile/BookCompleteActivity.kt
  app/src/main/java/org/mascota/ui/view/profile/ProfileCreateActivity.kt
  app/src/main/java/org/mascota/ui/view/profile/ProfileCreateBookFragment.kt
  app/src/main/java/org/mascota/ui/view/profile/ProfileCreatePetFragment.kt
  app/src/main/java/org/mascota/ui/view/profile/adapteer/HeroAdapter.kt
  app/src/main/java/org/mascota/ui/view/profile/adapteer/ProfileViewPagerAdapter.kt
  app/src/main/java/org/mascota/ui/view/profile/data/model/ResHero.kt
  app/src/main/java/org/mascota/util/AnimationUtil.kt
  app/src/main/java/org/mascota/util/CalendarUtil.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/color/selector_animal_text.xml
  app/src/main/res/color/selector_btn_text.xml
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_empty_img.xml
  app/src/main/res/drawable/ic_mascota_logo_white.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_quit_gray.xml
  app/src/main/res/drawable/ic_quit_orange.xml
  app/src/main/res/drawable/rectangle_border_orange_3.xml
  app/src/main/res/drawable/rectangle_bottom_gray_3.xml
  app/src/main/res/drawable/rectangle_fill_gray_3.xml
  app/src/main/res/drawable/rectangle_fill_gray_bottom_3.xml
  app/src/main/res/drawable/rectangle_fill_ivory_border_gray_3.xml
  app/src/main/res/drawable/rectangle_fill_ivory_border_orange_3.xml
  app/src/main/res/drawable/rectangle_fill_orange_3.xml
  app/src/main/res/drawable/rectangle_fill_orange_bottom_3.xml
  app/src/main/res/drawable/rectangle_fill_white_border_gray_3.xml
  app/src/main/res/drawable/rectangle_fill_white_border_orange_3.xml
  app/src/main/res/drawable/rectangle_progress.xml
  app/src/main/res/drawable/selector_animal_btn.xml
  app/src/main/res/drawable/selector_maco_btn.xml
  app/src/main/res/drawable/selector_profile_bottom_btn.xml
  app/src/main/res/drawable/selector_profile_et.xml
  app/src/main/res/drawable/selector_profile_ivory_btn.xml
  app/src/main/res/drawable/selector_profile_white_btn.xml
  app/src/main/res/drawable/selector_quit.xml
  app/src/main/res/layout/activity_book_complete.xml
  app/src/main/res/layout/activity_profile_create.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/fragment_profile_create_book.xml
  app/src/main/res/layout/fragment_profile_create_pet.xml
  app/src/main/res/layout/item_hero_pet.xml
  app/src/main/res/layout/layout_empty_image.xml
  app/src/main/res/layout/layout_plus_image.xml
  app/src/main/res/layout/layout_profile_bottom_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Done, P0, 🐶 mdb1217

#23 Feature/20 content detail activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/content/detail/ContentDetailActivity.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailDiaryAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailMonthAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/datasource/ContentDetailDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/datasource/LocalContentDetailDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/model/ContentDiaryInfoData.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/model/ContentMonthInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentDetailViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/res/drawable/rectangle_red_orange_radius_3.xml
  app/src/main/res/layout/activity_content_detail.xml
  app/src/main/res/layout/item_diary.xml
  app/src/main/res/layout/item_diary_month.xml
  app/src/main/res/layout/layout_book_diary.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#26 Feature/24 content edit activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/content/edit/adapter/ContentEditAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/edit/data/datasource/ContentEditDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/edit/data/datasource/LocalContentEditDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/edit/data/model/ContentEditInfoData.kt
  app/src/main/res/layout/activity_content_edit.xml
  app/src/main/res/layout/item_content_edit.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#28 Feature/25 init rainbow main
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/HomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/LocalHomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomePageInfoData.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/FarewellAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/HelpAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/datasource/LocalRainbowDataSource.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/datasource/RainbowDataSource.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/model/HelpInfoData.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/model/RainbowInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/java/org/mascota/util/CalendarUtil.kt
  app/src/main/java/org/mascota/util/DialogUtil.kt
  app/src/main/java/org/mascota/util/extension/ViewExt.kt
  app/src/main/res/drawable/ic_mascota_logo_orange.xml
  app/src/main/res/drawable/ic_question_mark.xml
  app/src/main/res/drawable/ic_rainbow_message.xml
  app/src/main/res/drawable/rectangle_border_gray_top.xml
  app/src/main/res/drawable/rectangle_border_gray_top_right.xml
  app/src/main/res/drawable/rectangle_fill_blue_3.xml
  app/src/main/res/drawable/rectangle_fill_blue_bottom_3.xml
  app/src/main/res/drawable/rectangle_fill_white_3.xml
  app/src/main/res/drawable/selector_farewell_bottom_btn.xml
  app/src/main/res/layout/fragment_rainbow.xml
  app/src/main/res/layout/item_farewell.xml
  app/src/main/res/layout/item_help_message.xml
  app/src/main/res/layout/layout_book_diary.xml
  app/src/main/res/layout/layout_farewell_dialog.xml
  app/src/main/res/layout/layout_help_message_dialog.xml
  app/src/main/res/layout/layout_profile_bottom_sheet.xml
  app/src/main/res/layout/layout_rainbow_page.xml
  app/src/main/res/layout/view_custom_book.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Done, P0, Review Required, 🐶 mdb1217

#35 Feature/34 complete farewell logic
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/FarewellAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellActivity.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBookFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellExplainFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/data/datasource/FarewellDataSource.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/data/datasource/LocalFarewellDataSource.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/data/model/PetInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/java/org/mascota/util/extension/ViewExt.kt
  app/src/main/res/layout/activity_farewell.xml
  app/src/main/res/layout/fragment_farewell_book.xml
  app/src/main/res/layout/fragment_farewell_explain.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, 🐶 mdb1217

#38 Feature/27 diary read activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/diary/read/DiaryReadActivity.kt
  app/src/main/java/org/mascota/ui/view/diary/read/adapter/EmotionImageAdapter.kt
  app/src/main/java/org/mascota/ui/view/diary/read/adapter/ProfileAdapter.kt
  app/src/main/java/org/mascota/ui/view/diary/read/data/datasource/LocalPetImageDataSource.kt
  app/src/main/java/org/mascota/ui/view/diary/read/data/datasource/PetImageDataSource.kt
  app/src/main/java/org/mascota/ui/view/diary/read/data/model/DiaryPetFeelingInfoData.kt
  app/src/main/res/drawable/rectangle_orange_top_radius_3.xml
  app/src/main/res/drawable/selector_pet_image_indicator.xml
  app/src/main/res/layout/activity_diary_read.xml
  app/src/main/res/layout/item_feeling.xml
  app/src/main/res/layout/item_small_profile.xml
  app/src/main/res/layout/layout_pet_image.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#42 Feature/39 writer emotion
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/MascotaApplication.kt
  app/src/main/java/org/mascota/data/local/MascotaSharedPreference.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/calendar/CalendarFragment.kt
  app/src/main/java/org/mascota/ui/view/diary/BindingAd.kt
  app/src/main/java/org/mascota/ui/view/diary/DiaryWriteActivity.kt
  app/src/main/java/org/mascota/ui/view/diary/DiaryWriterEmotionFragment.kt
  app/src/main/java/org/mascota/ui/view/diary/data/WriterEmotionData.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/FarewellAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellActivity.kt
  app/src/main/java/org/mascota/ui/viewmodel/DiaryViewModel.kt
  app/src/main/java/org/mascota/util/AnimationUtil.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/java/org/mascota/util/Event.kt
  app/src/main/res/color/selector_human_emotion_text.xml
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/drawable/ic_human_accept.xml
  app/src/main/res/drawable/ic_human_accept_on.xml
  app/src/main/res/drawable/ic_human_angry.xml
  app/src/main/res/drawable/ic_human_angry_on.xml
  app/src/main/res/drawable/ic_human_deny.xml
  app/src/main/res/drawable/ic_human_deny_on.xml
  app/src/main/res/drawable/ic_human_loss.xml
  app/src/main/res/drawable/ic_human_loss_on.xml
  app/src/main/res/drawable/ic_human_regret.xml
  app/src/main/res/drawable/ic_human_regret_on.xml
  app/src/main/res/drawable/ic_human_sad.xml
  app/src/main/res/drawable/ic_human_sad_on.xml
  app/src/main/res/drawable/selector_human_accept.xml
  app/src/main/res/drawable/selector_human_angry.xml
  app/src/main/res/drawable/selector_human_deny.xml
  app/src/main/res/drawable/selector_human_loss.xml
  app/src/main/res/drawable/selector_human_regret.xml
  app/src/main/res/drawable/selector_human_sad.xml
  app/src/main/res/layout/activity_diary_write.xml
  app/src/main/res/layout/fragment_diary_writer_emotion.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Done, P0, Review Required, 🐶 mdb1217

#46 Feature/30 content swipe button
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailDiaryAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailMonthAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/SwipeHelperCallback.kt
  app/src/main/res/layout/activity_content_detail.xml
  app/src/main/res/layout/item_diary.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#48 Feature/43 epilogue detail
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/diary/detail/EpilogueDetailActivity.kt
  app/src/main/res/drawable/ic_label.xml
  app/src/main/res/layout/activity_epilogue_detail.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐶 mdb1217

#49 Feature/47 connect dialog
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/content/edit/adapter/ContentEditAdapter.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/layout/layout_content_edit_dialog.xml
  app/src/main/res/layout/layout_help_message_dialog.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#50 Feature/45 diary solution
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/diary/DiarySolutionFragment.kt
  app/src/main/java/org/mascota/ui/view/diary/DiaryWriteActivity.kt
  app/src/main/java/org/mascota/ui/view/diary/DiaryWriterEmotionFragment.kt
  app/src/main/java/org/mascota/ui/viewmodel/DiaryViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/drawable/ic_human_accept_big.xml
  app/src/main/res/drawable/ic_human_angry_big.xml
  app/src/main/res/drawable/ic_human_deny_big.xml
  app/src/main/res/drawable/ic_human_loss_big.xml
  app/src/main/res/drawable/ic_human_regret_big.xml
  app/src/main/res/drawable/ic_human_sad_big.xml
  app/src/main/res/layout/activity_diary_write.xml
  app/src/main/res/layout/fragment_diary_solution.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐶 mdb1217

#53 Feature/52 login activity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/user/login/LoginActivity.kt
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#58 Feature/54 dots indicator
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/view/diary/read/DiaryReadActivity.kt
  app/src/main/res/layout/activity_diary_read.xml
  build.gradle
Labels: Done, P0, Review Required, 🐱 onpyeong

#62 Feature/59 mod layout
  app/src/main/java/org/mascota/ui/view/content/detail/ContentDetailActivity.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailDiaryAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailMonthAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/datasource/LocalContentDetailDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/model/ContentDiaryInfoData.kt
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/diary/read/DiaryReadActivity.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/adapter/HomeContentAdapter.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/drawable/ic_arrow_bottom.xml
  app/src/main/res/drawable/ic_back_small.xml
  app/src/main/res/drawable/ic_bg_grid.xml
  app/src/main/res/drawable/ic_dog_list.xml
  app/src/main/res/drawable/ic_hold.xml
  app/src/main/res/drawable/ic_next_small.xml
  app/src/main/res/drawable/ic_pictures.xml
  app/src/main/res/drawable/ic_plus_square.xml
  app/src/main/res/layout/activity_content_detail.xml
  app/src/main/res/layout/activity_content_edit.xml
  app/src/main/res/layout/activity_diary_read.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_content.xml
  app/src/main/res/layout/item_content_edit.xml
  app/src/main/res/layout/item_diary.xml
  app/src/main/res/layout/item_diary_month.xml
  app/src/main/res/layout/layout_diary_write.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#67 Feature/65 main rainbow network
  app/src/main/java/org/mascota/data/local/MascotaSharedPreference.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/HelpAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/datasource/LocalTempRainbowDataSource.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/datasource/TempRainbowDataSource.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/model/HelpInfoData.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/model/RainbowInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/java/org/mascota/util/CalendarUtil.kt
  app/src/main/res/layout/layout_rainbow_page.xml
Labels: Done, P0, Review Required, 🐶 mdb1217

#69 Feature/44 sign up acivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/ui/MainActivity.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/data/datasource/LocalRainbowDataSource.kt
  app/src/main/java/org/mascota/ui/view/signup/SignUpActivity.kt
  app/src/main/java/org/mascota/ui/view/signup/SignUpEndFragment.kt
  app/src/main/java/org/mascota/ui/view/signup/SignUpFragment.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/drawable-v24/rainbow.png
  app/src/main/res/drawable/btn_id.xml
  app/src/main/res/drawable/check.png
  app/src/main/res/drawable/ic_btn_doublecheck.xml
  app/src/main/res/drawable/ic_check_pwd.xml
  app/src/main/res/drawable/ic_icon_success.xml
  app/src/main/res/drawable/ic_icon_success2.xml
  app/src/main/res/drawable/ic_icon_success3.xml
  app/src/main/res/drawable/ic_logo_mascota.xml
  app/src/main/res/drawable/ment.png
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_sign_up.xml
  app/src/main/res/layout/fragment_sign_up_end.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐹 ssonghyun101

#72 Feature/64 home fragment network
  app/src/main/java/org/mascota/data/remote/api/HomeService.kt
  app/src/main/java/org/mascota/data/remote/model/response/home/ResHomePart1.kt
  app/src/main/java/org/mascota/data/remote/model/response/home/ResHomePart2.kt
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailDiaryAdapter.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/adapter/HomeContentAdapter.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomeDiaryInfoData.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/BestMomentAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/HelpAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBestMoment.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/drawable/ic_hold.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_content.xml
  app/src/main/res/layout/layout_book_diary.xml
  app/src/main/res/layout/layout_diary_write.xml
Labels: In Progress, P0, Review Required, 🐱 onpyeong

#73 Feature/70 signup network
  app/src/main/java/org/mascota/ui/view/signup/SignUpActivity.kt
  app/src/main/java/org/mascota/ui/view/signup/SignUpFragment.kt
  app/src/main/java/org/mascota/ui/viewmodel/UserViewModel.kt
  app/src/main/res/layout/activity_sign_up.xml
  app/src/main/res/layout/fragment_sign_up.xml
Labels: In Progress, P0, Review Required, 🐶 mdb1217

#74 Feature/64 home fragment network
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/adapter/HomeContentAdapter.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/HomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/datasource/LocalHomeBookDataSource.kt
  app/src/main/java/org/mascota/ui/view/home/data/model/HomeBookInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
Labels: In Progress, P0, Review Required, 🐱 onpyeong

#81 Feature/68 calendar network
  app/src/main/java/org/mascota/data/local/MascotaSharedPreference.kt
  app/src/main/java/org/mascota/data/remote/api/CalendarService.kt
  app/src/main/java/org/mascota/data/remote/api/RainbowService.kt
  app/src/main/java/org/mascota/data/remote/datasource/calendar/CalendarDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/calendar/RemoteCalendarDataSource.kt
  app/src/main/java/org/mascota/data/remote/model/response/calendar/ResCalendar.kt
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/base/BindingFragment.kt
  app/src/main/java/org/mascota/ui/view/calendar/CalendarFragment.kt
  app/src/main/java/org/mascota/ui/view/calendar/data/datasource/LocalTempCalendarDataSource.kt
  app/src/main/java/org/mascota/ui/view/calendar/data/datasource/TempCalendarDataSource.kt
  app/src/main/java/org/mascota/ui/view/custom/adapter/CalendarViewPagerAdapter.kt
  app/src/main/java/org/mascota/ui/view/custom/calendar/CalendarView.kt
  app/src/main/java/org/mascota/ui/view/custom/calendar/MonthView.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellExplainFragment.kt
  app/src/main/java/org/mascota/ui/viewmodel/CalendarViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/res/drawable/ic_cat_angry.xml
  app/src/main/res/drawable/ic_cat_boring.xml
  app/src/main/res/drawable/ic_cat_joy.xml
  app/src/main/res/drawable/ic_cat_love.xml
  app/src/main/res/drawable/ic_cat_sad.xml
  app/src/main/res/drawable/ic_cat_usual.xml
  app/src/main/res/drawable/ic_human_accept.xml
  app/src/main/res/drawable/ic_human_angry.xml
  app/src/main/res/drawable/ic_human_deny.xml
  app/src/main/res/drawable/ic_human_loss.xml
  app/src/main/res/drawable/ic_human_regret.xml
  app/src/main/res/drawable/ic_human_sad.xml
  app/src/main/res/layout/fragment_calendar.xml
  app/src/main/res/layout/item_date.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐶 mdb1217

#77 Feature/75 content detail network
  app/src/main/java/org/mascota/data/remote/api/ContentService.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/content/detail/ContentDetailActivity.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailDiaryAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailMonthAdapter.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/datasource/ContentDetailDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/datasource/LocalContentDetailDataSource.kt
  app/src/main/java/org/mascota/ui/view/content/detail/data/model/ContentMonthInfoData.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/adapter/HomeContentAdapter.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentViewModel.kt
  app/src/main/java/org/mascota/util/StringUtil.kt
  app/src/main/res/layout/item_diary_month.xml
Labels: In Progress, P0, Review Required, 🐱 onpyeong

#83 Feature/78 content edit network
  app/src/main/java/org/mascota/data/remote/api/ContentService.kt
  app/src/main/java/org/mascota/data/remote/datasource/content/ContentDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/content/RemoteContentDataSource.kt
  app/src/main/java/org/mascota/data/repository/content/ContentRepository.kt
  app/src/main/java/org/mascota/data/repository/content/ContentRepositoryImpl.kt
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/content/edit/adapter/ContentEditAdapter.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentViewModel.kt
Labels: In Progress, P0, Review Required, 🐱 onpyeong

#85 Feature/80 login network
  app/src/main/java/org/mascota/data/local/MascotaSharedPreference.kt
  app/src/main/java/org/mascota/ui/view/user/login/LoginActivity.kt
  app/src/main/java/org/mascota/ui/viewmodel/UserViewModel.kt
Labels: Done, 🐹 ssonghyun101

#87 Feature/82 farewell animal select network
  app/src/main/java/org/mascota/data/remote/api/RainbowService.kt
  app/src/main/java/org/mascota/data/remote/datasource/rainbow/RainbowDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/rainbow/RemoteRainbowDataSource.kt
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResFarewellSelect.kt
  app/src/main/java/org/mascota/data/repository/rainbow/RainbowRepository.kt
  app/src/main/java/org/mascota/data/repository/rainbow/RainbowRepositoryImpl.kt
  app/src/main/java/org/mascota/di/DataSourceModule.kt
  app/src/main/java/org/mascota/di/ViewModelModule.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/FarewellAdapter.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentViewModel.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/java/org/mascota/util/CalendarUtil.kt
Labels: Done, P0, 🐶 mdb1217

#89 Feature/86 part2 content network
  app/src/main/java/org/mascota/data/remote/api/ContentService.kt
  app/src/main/java/org/mascota/data/remote/model/response/content/ResContentList.kt
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/content/edit/adapter/ContentEditAdapter.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentViewModel.kt
Labels: In Progress, 🐹 ssonghyun101

#93 Feature/61 pet register network
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/data/local/MascotaSharedPreference.kt
  app/src/main/java/org/mascota/data/remote/api/ProfileService.kt
  app/src/main/java/org/mascota/data/remote/datasource/profile/ProfileDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/profile/RemoteProfileDataSource.kt
  app/src/main/java/org/mascota/data/remote/model/request/profile/ReqRegisterPet.kt
  app/src/main/java/org/mascota/data/repository/profile/ProfileRepository.kt
  app/src/main/java/org/mascota/data/repository/profile/ProfileRepositoryImpl.kt
  app/src/main/java/org/mascota/ui/view/diary/DiaryDetailWriteFragment.kt
  app/src/main/java/org/mascota/ui/view/profile/BookCompleteActivity.kt
  app/src/main/java/org/mascota/ui/view/profile/ProfileCreateActivity.kt
  app/src/main/java/org/mascota/ui/view/profile/ProfileCreateBookFragment.kt
  app/src/main/java/org/mascota/ui/view/profile/ProfileCreatePetFragment.kt
  app/src/main/java/org/mascota/ui/view/profile/adapteer/HeroAdapter.kt
  app/src/main/java/org/mascota/ui/view/profile/data/model/Pets.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBookFragment.kt
  app/src/main/java/org/mascota/ui/viewmodel/ProfileViewModel.kt
  app/src/main/java/org/mascota/util/ColorFilterUtil.kt
  app/src/main/java/org/mascota/util/extension/ViewExt.kt
  app/src/main/res/color/selector_date_text.xml
  app/src/main/res/drawable/selector_calendar.xml
  app/src/main/res/layout/activity_book_complete.xml
  app/src/main/res/layout/activity_profile_create.xml
  app/src/main/res/layout/fragment_profile_create_book.xml
  app/src/main/res/layout/fragment_profile_create_pet.xml
  app/src/main/res/layout/item_hero_pet.xml
  app/src/main/res/layout/layout_help_message_dialog.xml
  app/src/main/res/layout/layout_plus_image.xml
  app/src/main/res/layout/layout_profile_bottom_sheet.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, 🐶 mdb1217

#96 Feature/92 part2 all network
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/mascota/data/remote/api/ContentService.kt
  app/src/main/java/org/mascota/data/remote/datasource/content/ContentDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/content/RemoteContentDataSource.kt
  app/src/main/java/org/mascota/data/remote/model/request/content/ReqContentDelete.kt
  app/src/main/java/org/mascota/data/remote/model/response/content/ResContentAdd.kt
  app/src/main/java/org/mascota/data/remote/model/response/content/ResPart2ContentList.kt
  app/src/main/java/org/mascota/data/remote/model/response/home/ResHomePart2.kt
  app/src/main/java/org/mascota/data/repository/content/ContentRepository.kt
  app/src/main/java/org/mascota/data/repository/content/ContentRepositoryImpl.kt
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/home/Home2Activity.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/home/adapter/HomeContentAdapter.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentViewModel.kt
  app/src/main/java/org/mascota/ui/viewmodel/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/values/strings.xml
Labels: Done, 🐹 ssonghyun101

#98 Feature/88 best moment network
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResBestMoment.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/BestMomentAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBestMoment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/data/model/BestMomentInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/res/layout/activity_content_detail.xml
  app/src/main/res/layout/fragment_farewell_best_moment.xml
  app/src/main/res/values/strings.xml
Labels: In Progress, P0, Review Required, 🐱 onpyeong

#100 Feature/99 diary detail 2 network
  app/src/main/java/org/mascota/data/remote/api/ContentService.kt
  app/src/main/java/org/mascota/data/remote/datasource/content/ContentDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/content/RemoteContentDataSource.kt
  app/src/main/java/org/mascota/data/remote/model/response/content/ResPart2ContentDetail.kt
  app/src/main/java/org/mascota/data/repository/content/ContentRepository.kt
  app/src/main/java/org/mascota/data/repository/content/ContentRepositoryImpl.kt
  app/src/main/java/org/mascota/ui/view/content/detail/ContentDetailActivity.kt
  app/src/main/java/org/mascota/ui/view/content/detail/adapter/ContentDetailDiaryAdapter.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/diary/read/DiaryReadActivity.kt
  app/src/main/java/org/mascota/ui/view/diary/read/adapter/EmotionImageAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/BestMomentAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBestMoment.kt
  app/src/main/java/org/mascota/ui/viewmodel/ContentViewModel.kt
  app/src/main/java/org/mascota/ui/viewmodel/DiaryViewModel.kt
  app/src/main/res/layout/activity_content_edit.xml
  app/src/main/res/layout/activity_diary_read.xml
  app/src/main/res/layout/fragment_farewell_best_moment.xml
  app/src/main/res/layout/item_diary.xml
  app/src/main/res/layout/layout_rainbow_page.xml
  app/src/main/res/values/strings.xml
Labels: Done, P0, Review Required, 🐱 onpyeong

#102 Feature/97 epilogue post network
  .idea/misc.xml
  app/src/main/java/org/mascota/data/remote/api/RainbowService.kt
  app/src/main/java/org/mascota/data/remote/datasource/rainbow/RainbowDataSource.kt
  app/src/main/java/org/mascota/data/remote/datasource/rainbow/RemoteRainbowDataSource.kt
  app/src/main/java/org/mascota/data/remote/model/request/rainbow/ReqRainbowEpilogue.kt
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResFarewellQuit.kt
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResRainbowBook.kt
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResRainbowContent.kt
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResRainbowEpilogue.kt
  app/src/main/java/org/mascota/data/repository/rainbow/RainbowRepository.kt
  app/src/main/java/org/mascota/data/repository/rainbow/RainbowRepositoryImpl.kt
  app/src/main/java/org/mascota/ui/view/home/Home2Activity.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/epilogue/EpilogueWriteActivity.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellActivity.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBookFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellExplainFragment.kt
  app/src/main/java/org/mascota/ui/view/user/login/LoginActivity.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/res/drawable/ic_illust_rainbow_cat_big.xml
  app/src/main/res/drawable/ic_illust_rainbow_human.xml
  app/src/main/res/layout/activity_epilogue_write.xml
  app/src/main/res/layout/activity_home2.xml
  app/src/main/res/layout/fragment_farewell_book.xml
  app/src/main/res/layout/fragment_farewell_explain.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_rainbow.xml
  app/src/main/res/values/strings.xml
Labels: Done, 🐹 ssonghyun101

#103 Hotfix/101 farewell pet network
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResBestMoment.kt
  app/src/main/java/org/mascota/data/remote/model/response/rainbow/ResFarewellSelect.kt
  app/src/main/java/org/mascota/ui/view/custom/book/BookView.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/BestMomentAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/adapter/FarewellAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBestMoment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/data/model/BestMomentInfoData.kt
  app/src/main/java/org/mascota/ui/viewmodel/DiaryViewModel.kt
  app/src/main/java/org/mascota/ui/viewmodel/RainbowViewModel.kt
  app/src/main/java/org/mascota/util/BindingAdapter.kt
  app/src/main/res/layout/item_farewell.xml
  app/src/main/res/layout/layout_rainbow_page.xml
Labels: Done, P0, 🐱 onpyeong

#106 Feature/105 refactor all code(appjam)
  app/build.gradle
  app/release/output-metadata.json
  app/src/main/java/org/mascota/ui/MainActivity.kt
  app/src/main/java/org/mascota/ui/view/calendar/CalendarFragment.kt
  app/src/main/java/org/mascota/ui/view/content/detail/ContentDetailActivity.kt
  app/src/main/java/org/mascota/ui/view/content/edit/ContentEditActivity.kt
  app/src/main/java/org/mascota/ui/view/diary/adpter/ImageAdapter.kt
  app/src/main/java/org/mascota/ui/view/diary/adpter/SelectEmotionAdapter.kt
  app/src/main/java/org/mascota/ui/view/diary/read/DiaryReadActivity.kt
  app/src/main/java/org/mascota/ui/view/home/Home2Activity.kt
  app/src/main/java/org/mascota/ui/view/home/HomeFragment.kt
  app/src/main/java/org/mascota/ui/view/profile/adapteer/HeroAdapter.kt
  app/src/main/java/org/mascota/ui/view/rainbow/RainbowFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/epilogue/EpilogueWriteActivity.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellActivity.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBestMoment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBestMomentFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellBookFragment.kt
  app/src/main/java/org/mascota/ui/view/rainbow/farewell/FarewellExplainFragment.kt
  app/src/main/java/org/mascota/util/DialogUtil.kt
  app/src/main/res/drawable/ic_illust_index.xml
  app/src/main/res/drawable/ic_illust_rainbow.xml
  app/src/main/res/layout/activity_content_edit.xml
  app/src/main/res/layout/activity_home2.xml
  app/src/main/res/layout/fragment_diary_writer_emotion.xml
  app/src/main/res/layout/fragment_farewell_best_moment.xml
  app/src/main/res/layout/fragment_farewell_explain.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_farewell.xml
  app/src/main/res/layout/layout_loading.xml
  app/src/main/res/raw/loading_block.json
  app/src/main/res/values/dimens.xml
Labels: Done, P0, Review Required, 🐶 mdb1217
